[features]
seeds = false
[programs.localnet]
solana_twitter = "J6r6DAVEEU1oWGTwysNtkKdrV1pnfUGCub9MvXEoxSTU"

[programs.testnet]
solana_twitter = "J6r6DAVEEU1oWGTwysNtkKdrV1pnfUGCub9MvXEoxSTU"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "testnet"
wallet = "/home/bojko/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"
